In [11]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

In [3]:
from sklearn.datasets import make_regression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [5]:
x,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [13]:
df = pd.DataFrame({'column1':x[:,0],'column2':x[:,1],'column__y':y})

In [14]:
df.shape

(100, 3)

In [15]:
df.sample(5)

     column1   column2   column__y
19  0.323425  0.194427  116.711888
96 -0.295098 -0.699214 -114.076054
36  0.145696  0.647486   24.395483
99 -1.232931  1.861819  -27.058308
62 -0.390862  0.972252   -8.831892

In [16]:
# Scatter plot 

fig = px.scatter_3d(df, x='column1',y='column2',z='column__y')

fig.show()

In [17]:
# Train test split 

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [18]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [19]:
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [27]:
print(mean_absolute_error(y_test,y_pred)) # Mean Absolute Error
print(mean_squared_error(y_test,y_pred)) # Mean Squared Error
print(r2_score(y_test,y_pred))  # R2 score

37.62761806551843
2136.962459546157
0.8375435292579564

In [28]:
lr.coef_

array([84.93417982, 57.49529677])

In [32]:
lr.intercept_

np.float64(-3.12161096258017)

In [33]:
df

     column1   column2   column__y
0   0.932142  0.022720  123.685999
1  -2.302942 -0.353929 -165.968769
2  -1.362444 -0.177749  -89.803375
3   0.972961 -0.336919  152.481285
4  -0.026398 -0.732536  -59.758577
..       ...       ...         ...
95 -0.713836  0.279137  -22.608787
96 -0.295098 -0.699214 -114.076054
97  0.825270 -0.373215   -8.330764
98 -0.232282 -0.845481  -59.512954
99 -1.232931  1.861819  -27.058308

[100 rows x 3 columns]