In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [5]:
df.shape

(891, 4)

In [6]:
df.isnull().sum()

Age         177
Pclass        0
Fare          0
Survived      0
dtype: int64

<h2>train-test-split</h2>

In [7]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [9]:
x_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [10]:
knn = KNNImputer(n_neighbors=3,weights='distance')

x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [12]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)

y_pred = lr.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.7150837988826816

<h2>Comaparison with Simple IMputer mean</h2>

In [13]:
si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [14]:
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)

y_pred2 = lr.predict(x_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978